// <auto-generated />
using System;
using Core.Infrastructure.Identity.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Infrastructure.Migrations.IdentityDb
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20241125230212_IdentityInitialMigration")]
    partial class IdentityInitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Infrastructure.Identity.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "42df1250-85ef-4683-9046-6f2e5405ee3a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e4e058bc-4223-45ee-9982-be0786bca5d2",
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAED+YZuc/3H4sib4v1ITXTs8j+dXbhiakkJgEvaChASaHawCb0s1YUZdOUNLw98Kf+Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b296f64e-bb37-4b00-aefd-c7fbf310c0e6",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        },
                        new
                        {
                            Id = "48a3b0de-d24d-4879-a528-ddaf38580270",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bfb9a6a0-ebeb-4132-81f4-1a367df4c5de",
                            Email = "naissuscompanyadmin@localhost.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NAISSUSCOMPANYADMIN@LOCALHOST.COM",
                            NormalizedUserName = "NAISSUSCOMPANYADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN63iXou6lRrv9XzbguIsI1SpgyEBe3wJU6W10bIJD6uBgBeR8l0tq5N0P4OC9OSnw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "27ef1998-f42b-48d8-b8c4-a47ee2aff8ba",
                            TwoFactorEnabled = false,
                            UserName = "naissuscompanyadmin@localhost.com"
                        },
                        new
                        {
                            Id = "2499bc5a-0f33-4f67-b521-5829679ee7ff",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "512cf4b6-4b5f-4bb7-9ab4-ee719786fd8f",
                            Email = "filip.dimitrijevic@localhost.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "FILIP.DIMITRIJEVIC@LOCALHOST.COM",
                            NormalizedUserName = "FILIP.DIMITRIJEVIC@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEApcdI06Zv75TOdd5DSjgd/P4rjVIP/MnQJlnBGHwLfxoPiJ4kCA4myxl3vNPPdvoA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "452fc2eb-c0ba-419d-9995-6aed57a38b55",
                            TwoFactorEnabled = false,
                            UserName = "filip.dimitrijevic@localhost.com"
                        },
                        new
                        {
                            Id = "306627f3-c902-4d48-a6f3-d83db48df2c6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "36194ca4-d13b-4b1c-aee4-28342476496e",
                            Email = "hr@localhost.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "HR@LOCALHOST.COM",
                            NormalizedUserName = "HR@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENh8KQgRTk9h9F7St+UiP+scJaGa7eCpQapkOJXqqBEdYQtdifmId8OhLUq23UrSIA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3ba7a282-fa40-4a72-9e31-ba199b33a831",
                            TwoFactorEnabled = false,
                            UserName = "hr@localhost.com"
                        },
                        new
                        {
                            Id = "e19c3b4a-b3ec-49a8-9790-5d15d9b8de96",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9ccd66ce-08b8-4c94-abe4-000509593713",
                            Email = "marko.stoiljkovic@localhost.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MARKO.STOILJKOVIC@LOCALHOST.COM",
                            NormalizedUserName = "MARKO.STOILJKOVIC@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEE5ZHj1XzdPXoj1b5r5GLZacNQ66/kGkr5dS2nR28A+8uIiymvbz2f9bK/D7pLYkvQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2c3f9b80-ac49-498b-be63-16ed81d23ce4",
                            TwoFactorEnabled = false,
                            UserName = "marko.stoiljkovic@localhost.com"
                        },
                        new
                        {
                            Id = "985fe5c1-deb8-4082-863a-840037477bc5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "60134e52-1978-4106-9f8f-3445d881053d",
                            Email = "sara.dimitrijevic@localhost.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SARA.DIMITRIJEVIC@LOCALHOST.COM",
                            NormalizedUserName = "SARA.DIMITRIJEVIC@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFSR5oBgIHY5mdhhOBbSzJ/l9qYCffwgljWCe4ZMStvB6V0Nir0g0w871NegHkbqtg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6657fabf-3cb8-43f9-9e80-0ce268a3819a",
                            TwoFactorEnabled = false,
                            UserName = "sara.dimitrijevic@localhost.com"
                        },
                        new
                        {
                            Id = "88ea1648-4810-4e04-81f9-cfdff02bbd22",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "adbb6c0a-e464-4527-ad10-1f7b334c845d",
                            Email = "petar.markovic@localhost.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PETAR.MARKOVIC@LOCALHOST.COM",
                            NormalizedUserName = "PETAR.MARKOVIC@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFUz+a0eqwBBRj45qzrCE6sYFTPHe/1NbhP4eDypFYjIoA2QZnXvl0Mfl++zrj0fXQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2ce2d770-50a0-401c-b822-7eb115ffb530",
                            TwoFactorEnabled = false,
                            UserName = "petar.markovic@localhost.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "995d5439-2b54-458a-b08d-e0f289255a96",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "ebc687e2-03df-4448-b79e-32e3e39de6bc",
                            Name = "Company Administrator",
                            NormalizedName = "COMPANY ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "2ed7c2e3-d4ad-4222-9439-1700379ea772",
                            Name = "HR",
                            NormalizedName = "HR"
                        },
                        new
                        {
                            Id = "dd70f100-6753-494a-9382-1dd5ef51d4b6",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "42df1250-85ef-4683-9046-6f2e5405ee3a",
                            RoleId = "995d5439-2b54-458a-b08d-e0f289255a96"
                        },
                        new
                        {
                            UserId = "2499bc5a-0f33-4f67-b521-5829679ee7ff",
                            RoleId = "dd70f100-6753-494a-9382-1dd5ef51d4b6"
                        },
                        new
                        {
                            UserId = "306627f3-c902-4d48-a6f3-d83db48df2c6",
                            RoleId = "2ed7c2e3-d4ad-4222-9439-1700379ea772"
                        },
                        new
                        {
                            UserId = "48a3b0de-d24d-4879-a528-ddaf38580270",
                            RoleId = "ebc687e2-03df-4448-b79e-32e3e39de6bc"
                        },
                        new
                        {
                            UserId = "e19c3b4a-b3ec-49a8-9790-5d15d9b8de96",
                            RoleId = "dd70f100-6753-494a-9382-1dd5ef51d4b6"
                        },
                        new
                        {
                            UserId = "985fe5c1-deb8-4082-863a-840037477bc5",
                            RoleId = "dd70f100-6753-494a-9382-1dd5ef51d4b6"
                        },
                        new
                        {
                            UserId = "88ea1648-4810-4e04-81f9-cfdff02bbd22",
                            RoleId = "dd70f100-6753-494a-9382-1dd5ef51d4b6"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Core.Infrastructure.Identity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Core.Infrastructure.Identity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Infrastructure.Identity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Core.Infrastructure.Identity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
