// <auto-generated />
using System;
using Core.Infrastructure.Persistence.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Infrastructure.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20241126192039_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CVPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CVPath = "/uploads/john_doe_cv.pdf",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 26, 19, 20, 39, 225, DateTimeKind.Utc).AddTicks(2539),
                            DateOfBirth = new DateOnly(1990, 5, 15),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Note = "Candidate shows strong skills in backend development.",
                            Rating = 4,
                            Seniority = "Senior",
                            StackPosition = "Backend",
                            Uid = new Guid("afc65760-c53a-4188-9c37-65461d53977e")
                        },
                        new
                        {
                            Id = 2,
                            CVPath = "/uploads/alice_smith_cv.pdf",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 26, 19, 20, 39, 225, DateTimeKind.Utc).AddTicks(2569),
                            DateOfBirth = new DateOnly(1985, 12, 30),
                            Email = "alice.smith@example.com",
                            FirstName = "Alice",
                            LastName = "Smith",
                            Note = "Experienced project manager with a strong background in Agile methodologies.",
                            Rating = 5,
                            Seniority = "Senior",
                            StackPosition = "Fullstack",
                            Uid = new Guid("c90cb5c7-10d2-4a24-b485-52c448bf4f46")
                        },
                        new
                        {
                            Id = 3,
                            CVPath = "/uploads/michael_johnson_cv.pdf",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 26, 19, 20, 39, 225, DateTimeKind.Utc).AddTicks(2570),
                            DateOfBirth = new DateOnly(1992, 4, 10),
                            Email = "michael.johnson@example.com",
                            FirstName = "Michael",
                            LastName = "Johnson",
                            Note = "Front-end developer with expertise in React and Vue.js.",
                            Rating = 3,
                            Seniority = "Junior",
                            StackPosition = "Unknown",
                            Uid = new Guid("1d549dd0-4d19-490c-afd7-e3feb2c565f2")
                        },
                        new
                        {
                            Id = 4,
                            CVPath = "/uploads/emma_williams_cv.pdf",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 26, 19, 20, 39, 225, DateTimeKind.Utc).AddTicks(2574),
                            DateOfBirth = new DateOnly(1988, 8, 25),
                            Email = "emma.williams@example.com",
                            FirstName = "Emma",
                            LastName = "Williams",
                            Note = "Full-stack developer with strong skills in Node.js and .NET Core.",
                            Rating = 4,
                            Seniority = "Junior",
                            StackPosition = "Fullstack",
                            Uid = new Guid("ca7facd0-23a7-46b7-833e-8c69992fa234")
                        },
                        new
                        {
                            Id = 5,
                            CVPath = "/uploads/david_brown_cv.pdf",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 26, 19, 20, 39, 225, DateTimeKind.Utc).AddTicks(2576),
                            DateOfBirth = new DateOnly(1995, 11, 15),
                            Email = "david.brown@example.com",
                            FirstName = "David",
                            LastName = "Brown",
                            Note = "DevOps engineer with experience in CI/CD pipelines and containerization.",
                            Rating = 5,
                            Seniority = "Mid",
                            StackPosition = "DevOps",
                            Uid = new Guid("8f80e5fb-51c7-4f7c-ba05-3a4e7aab0d7e")
                        });
                });

            modelBuilder.Entity("Core.Domain.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 11, 26, 20, 20, 39, 225, DateTimeKind.Local).AddTicks(4066),
                            Name = "Naissus Tech",
                            Uid = new Guid("da4fdc93-facb-45e2-9170-cb94d01c42fb")
                        });
                });

            modelBuilder.Entity("Core.Domain.LeaveDistribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeUid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<int>("RemainingDays")
                        .HasColumnType("int");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveDistributions");
                });

            modelBuilder.Entity("Core.Domain.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRequested")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<string>("RequestComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestingEmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReserveOnly")
                        .HasColumnType("bit");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("Core.Domain.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DefaultDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("RequiresHRApproval")
                        .HasColumnType("bit");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LeaveTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 11, 26, 20, 20, 39, 225, DateTimeKind.Local).AddTicks(5439),
                            DefaultDays = 21,
                            Name = "Vacation",
                            RequiresHRApproval = true,
                            Uid = new Guid("3034d942-0fee-467f-a288-d680fce6aa00")
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 11, 26, 20, 20, 39, 225, DateTimeKind.Local).AddTicks(5454),
                            DefaultDays = 15,
                            Name = "Old Vacation",
                            RequiresHRApproval = true,
                            Uid = new Guid("10ec6094-46a4-4963-8a44-d68c6052048d")
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 11, 26, 20, 20, 39, 225, DateTimeKind.Local).AddTicks(5456),
                            DefaultDays = 15,
                            Name = "Remote Work",
                            RequiresHRApproval = true,
                            Uid = new Guid("54d970f8-bdb4-47bc-b932-3588b80637db")
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 11, 26, 20, 20, 39, 225, DateTimeKind.Local).AddTicks(5458),
                            DefaultDays = 365,
                            Name = "Sick Leave",
                            RequiresHRApproval = false,
                            Uid = new Guid("0b70c087-5333-4705-8617-fca6b4851f4a")
                        });
                });

            modelBuilder.Entity("Core.Domain.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LeadUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 26, 20, 20, 39, 225, DateTimeKind.Local).AddTicks(7038),
                            LeadUid = new Guid("306627f3-c902-4d48-a6f3-d83db48df2c6"),
                            Name = "GBI",
                            Uid = new Guid("9fe876b5-0429-42e0-a205-1f6d9c2a7cb5")
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 26, 20, 20, 39, 225, DateTimeKind.Local).AddTicks(7062),
                            LeadUid = new Guid("985fe5c1-deb8-4082-863a-840037477bc5"),
                            Name = "GOAT",
                            Uid = new Guid("bd7746a3-1385-4d0e-8fb7-3e19a0f360c1")
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 26, 20, 20, 39, 225, DateTimeKind.Local).AddTicks(7067),
                            LeadUid = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Support",
                            Uid = new Guid("67f55a17-fc74-4c83-ad93-e52937c2499c")
                        });
                });

            modelBuilder.Entity("Core.Domain.TeamUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TeamUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserUid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TeamsUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 11, 26, 19, 20, 39, 225, DateTimeKind.Utc).AddTicks(7980),
                            TeamUid = new Guid("9fe876b5-0429-42e0-a205-1f6d9c2a7cb5"),
                            Uid = new Guid("abc93719-bbcf-4a3d-9e79-39703e4f529a"),
                            UserUid = new Guid("2499bc5a-0f33-4f67-b521-5829679ee7ff")
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 11, 26, 19, 20, 39, 225, DateTimeKind.Utc).AddTicks(7992),
                            TeamUid = new Guid("9fe876b5-0429-42e0-a205-1f6d9c2a7cb5"),
                            Uid = new Guid("2b92261b-0ea0-478f-987a-fcc02ab4554a"),
                            UserUid = new Guid("e19c3b4a-b3ec-49a8-9790-5d15d9b8de96")
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 11, 26, 19, 20, 39, 225, DateTimeKind.Utc).AddTicks(7995),
                            TeamUid = new Guid("67f55a17-fc74-4c83-ad93-e52937c2499c"),
                            Uid = new Guid("8eb7d426-dc9c-4fc5-9685-5409033d926c"),
                            UserUid = new Guid("306627f3-c902-4d48-a6f3-d83db48df2c6")
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 11, 26, 19, 20, 39, 225, DateTimeKind.Utc).AddTicks(7999),
                            TeamUid = new Guid("bd7746a3-1385-4d0e-8fb7-3e19a0f360c1"),
                            Uid = new Guid("21c00174-7f5f-4364-bb02-3c69abb64cbb"),
                            UserUid = new Guid("985fe5c1-deb8-4082-863a-840037477bc5")
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 11, 26, 19, 20, 39, 225, DateTimeKind.Utc).AddTicks(8006),
                            TeamUid = new Guid("bd7746a3-1385-4d0e-8fb7-3e19a0f360c1"),
                            Uid = new Guid("2bc07398-ca94-4274-98a6-33041ea66b19"),
                            UserUid = new Guid("88ea1648-4810-4e04-81f9-cfdff02bbd22")
                        });
                });

            modelBuilder.Entity("Core.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateOfEmployment")
                        .HasColumnType("date");

                    b.Property<Guid?>("DedicatedHR")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsTeamLead")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ReligiousHolidayDay")
                        .HasColumnType("date");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TeamLeadUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyEmail = "admin@localhost.com",
                            CreatedDate = new DateTime(2024, 11, 26, 19, 20, 39, 225, DateTimeKind.Utc).AddTicks(8917),
                            DateOfBirth = new DateOnly(1, 1, 1),
                            DateOfEmployment = new DateOnly(1, 1, 1),
                            FirstName = "System",
                            IsTeamLead = false,
                            LastName = "Admin",
                            Seniority = "Unknown",
                            StackPosition = "Unknown",
                            Uid = new Guid("42df1250-85ef-4683-9046-6f2e5405ee3a")
                        },
                        new
                        {
                            Id = 2,
                            CompanyEmail = "naissuscompanyadmin@localhost.com",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 26, 19, 20, 39, 225, DateTimeKind.Utc).AddTicks(8924),
                            DateOfBirth = new DateOnly(1, 1, 1),
                            DateOfEmployment = new DateOnly(1, 1, 1),
                            FirstName = "Company",
                            IsTeamLead = false,
                            LastName = "Admin",
                            Seniority = "Unknown",
                            StackPosition = "Unknown",
                            Uid = new Guid("48a3b0de-d24d-4879-a528-ddaf38580270")
                        },
                        new
                        {
                            Id = 3,
                            CompanyEmail = "filip.dimitrijevic@localhost.com",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 26, 19, 20, 39, 225, DateTimeKind.Utc).AddTicks(8927),
                            DateOfBirth = new DateOnly(1995, 1, 14),
                            DateOfEmployment = new DateOnly(2021, 1, 10),
                            DedicatedHR = new Guid("306627f3-c902-4d48-a6f3-d83db48df2c6"),
                            FirstName = "Filip",
                            IsTeamLead = false,
                            LastName = "Dimitrijevic",
                            PhoneNumber = "0692509999",
                            ReligiousHolidayDay = new DateOnly(1900, 1, 12),
                            Seniority = "Mid",
                            StackPosition = "Backend",
                            TeamLeadUid = new Guid("e19c3b4a-b3ec-49a8-9790-5d15d9b8de96"),
                            Uid = new Guid("2499bc5a-0f33-4f67-b521-5829679ee7ff")
                        },
                        new
                        {
                            Id = 4,
                            CompanyEmail = "hr@localhost.com",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 26, 19, 20, 39, 225, DateTimeKind.Utc).AddTicks(8933),
                            DateOfBirth = new DateOnly(1990, 1, 1),
                            DateOfEmployment = new DateOnly(2022, 1, 1),
                            FirstName = "Bojana",
                            IsTeamLead = false,
                            LastName = "Stoiljkovic",
                            Seniority = "Mid",
                            StackPosition = "HR",
                            Uid = new Guid("306627f3-c902-4d48-a6f3-d83db48df2c6")
                        },
                        new
                        {
                            Id = 5,
                            CompanyEmail = "marko.stoiljkovic@localhost.com",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 26, 19, 20, 39, 225, DateTimeKind.Utc).AddTicks(8935),
                            DateOfBirth = new DateOnly(1989, 1, 1),
                            DateOfEmployment = new DateOnly(2015, 1, 1),
                            DedicatedHR = new Guid("306627f3-c902-4d48-a6f3-d83db48df2c6"),
                            FirstName = "Marko",
                            IsTeamLead = true,
                            LastName = "Stoiljkovic",
                            PhoneNumber = "0638888888",
                            ReligiousHolidayDay = new DateOnly(1900, 1, 12),
                            Seniority = "Lead",
                            StackPosition = "ProjectManager",
                            Uid = new Guid("e19c3b4a-b3ec-49a8-9790-5d15d9b8de96")
                        },
                        new
                        {
                            Id = 6,
                            CompanyEmail = "sara.dimitrijevic@localhost.com",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 26, 19, 20, 39, 225, DateTimeKind.Utc).AddTicks(8938),
                            DateOfBirth = new DateOnly(1999, 2, 12),
                            DateOfEmployment = new DateOnly(2020, 1, 1),
                            DedicatedHR = new Guid("306627f3-c902-4d48-a6f3-d83db48df2c6"),
                            FirstName = "Sara",
                            IsTeamLead = true,
                            LastName = "Dimitrijevic",
                            PhoneNumber = "0623333344",
                            ReligiousHolidayDay = new DateOnly(1900, 1, 12),
                            Seniority = "Mid",
                            StackPosition = "ProjectManager",
                            Uid = new Guid("985fe5c1-deb8-4082-863a-840037477bc5")
                        },
                        new
                        {
                            Id = 7,
                            CompanyEmail = "petar.markovic@localhost.com",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 26, 19, 20, 39, 225, DateTimeKind.Utc).AddTicks(8940),
                            DateOfBirth = new DateOnly(1998, 12, 5),
                            DateOfEmployment = new DateOnly(2021, 1, 1),
                            DedicatedHR = new Guid("306627f3-c902-4d48-a6f3-d83db48df2c6"),
                            FirstName = "Petar",
                            IsTeamLead = false,
                            LastName = "Markovic",
                            ReligiousHolidayDay = new DateOnly(1900, 1, 12),
                            Seniority = "Senior",
                            StackPosition = "Backend",
                            TeamLeadUid = new Guid("985fe5c1-deb8-4082-863a-840037477bc5"),
                            Uid = new Guid("88ea1648-4810-4e04-81f9-cfdff02bbd22")
                        });
                });

            modelBuilder.Entity("Core.Domain.Candidate", b =>
                {
                    b.HasOne("Core.Domain.Company", "Company")
                        .WithMany("Candidates")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Core.Domain.LeaveDistribution", b =>
                {
                    b.HasOne("Core.Domain.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("Core.Domain.LeaveRequest", b =>
                {
                    b.HasOne("Core.Domain.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Core.Domain.Common.DateRange", "Duration", b1 =>
                        {
                            b1.Property<int>("LeaveRequestId")
                                .HasColumnType("int");

                            b1.Property<DateOnly>("End")
                                .HasColumnType("date");

                            b1.Property<int>("LengthInDays")
                                .HasColumnType("int");

                            b1.Property<DateOnly>("Start")
                                .HasColumnType("date");

                            b1.HasKey("LeaveRequestId");

                            b1.ToTable("LeaveRequests");

                            b1.WithOwner()
                                .HasForeignKey("LeaveRequestId");
                        });

                    b.Navigation("Duration")
                        .IsRequired();

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("Core.Domain.Team", b =>
                {
                    b.HasOne("Core.Domain.Company", "Company")
                        .WithMany("Teams")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Core.Domain.User", b =>
                {
                    b.HasOne("Core.Domain.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Core.Domain.Company", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("Teams");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
