// <auto-generated />
using System;
using Core.Infrastructure.Persistence.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Infrastructure.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20241125233236_AddedToCandidatesCompany")]
    partial class AddedToCandidatesCompany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CVPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CVPath = "/uploads/john_doe_cv.pdf",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 25, 23, 32, 36, 331, DateTimeKind.Utc).AddTicks(2660),
                            DateOfBirth = new DateOnly(1990, 5, 15),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Note = "Candidate shows strong skills in backend development.",
                            Rating = 4,
                            Seniority = "Senior",
                            StackPosition = "Backend",
                            Uid = new Guid("8f39dd6e-6316-48bb-9107-d0239329cc57")
                        },
                        new
                        {
                            Id = 2,
                            CVPath = "/uploads/alice_smith_cv.pdf",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 25, 23, 32, 36, 331, DateTimeKind.Utc).AddTicks(2698),
                            DateOfBirth = new DateOnly(1985, 12, 30),
                            Email = "alice.smith@example.com",
                            FirstName = "Alice",
                            LastName = "Smith",
                            Note = "Experienced project manager with a strong background in Agile methodologies.",
                            Rating = 5,
                            Seniority = "Senior",
                            StackPosition = "Fullstack",
                            Uid = new Guid("3e42ea11-19a8-4344-b7f4-c036102efb22")
                        },
                        new
                        {
                            Id = 3,
                            CVPath = "/uploads/michael_johnson_cv.pdf",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 25, 23, 32, 36, 331, DateTimeKind.Utc).AddTicks(2700),
                            DateOfBirth = new DateOnly(1992, 4, 10),
                            Email = "michael.johnson@example.com",
                            FirstName = "Michael",
                            LastName = "Johnson",
                            Note = "Front-end developer with expertise in React and Vue.js.",
                            Rating = 3,
                            Seniority = "Junior",
                            StackPosition = "Unknown",
                            Uid = new Guid("72801d43-78e2-4571-ae2a-c7481f3eccda")
                        },
                        new
                        {
                            Id = 4,
                            CVPath = "/uploads/emma_williams_cv.pdf",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 25, 23, 32, 36, 331, DateTimeKind.Utc).AddTicks(2703),
                            DateOfBirth = new DateOnly(1988, 8, 25),
                            Email = "emma.williams@example.com",
                            FirstName = "Emma",
                            LastName = "Williams",
                            Note = "Full-stack developer with strong skills in Node.js and .NET Core.",
                            Rating = 4,
                            Seniority = "Junior",
                            StackPosition = "Fullstack",
                            Uid = new Guid("3f0943d0-50f6-4fbe-bcc0-70d7de852ef4")
                        },
                        new
                        {
                            Id = 5,
                            CVPath = "/uploads/david_brown_cv.pdf",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 25, 23, 32, 36, 331, DateTimeKind.Utc).AddTicks(2705),
                            DateOfBirth = new DateOnly(1995, 11, 15),
                            Email = "david.brown@example.com",
                            FirstName = "David",
                            LastName = "Brown",
                            Note = "DevOps engineer with experience in CI/CD pipelines and containerization.",
                            Rating = 5,
                            Seniority = "Mid",
                            StackPosition = "DevOps",
                            Uid = new Guid("596a7762-ed58-4e54-bd58-a31095dd911e")
                        });
                });

            modelBuilder.Entity("Core.Domain.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 11, 26, 0, 32, 36, 331, DateTimeKind.Local).AddTicks(3541),
                            Name = "Naissus Tech",
                            Uid = new Guid("da4fdc93-facb-45e2-9170-cb94d01c42fb")
                        });
                });

            modelBuilder.Entity("Core.Domain.LeaveDistribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeUid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<int>("RemainingDays")
                        .HasColumnType("int");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveDistributions");
                });

            modelBuilder.Entity("Core.Domain.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRequested")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<string>("RequestComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestingEmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReserveOnly")
                        .HasColumnType("bit");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("Core.Domain.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DefaultDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("RequiresHRApproval")
                        .HasColumnType("bit");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LeaveTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 11, 26, 0, 32, 36, 331, DateTimeKind.Local).AddTicks(5160),
                            DefaultDays = 21,
                            Name = "Vacation",
                            RequiresHRApproval = true,
                            Uid = new Guid("b5b674a6-0f22-424f-92a0-a206daeb385c")
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 11, 26, 0, 32, 36, 331, DateTimeKind.Local).AddTicks(5173),
                            DefaultDays = 15,
                            Name = "Old Vacation",
                            RequiresHRApproval = true,
                            Uid = new Guid("887f46af-cbe5-46f0-908b-7b086cb57ccf")
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 11, 26, 0, 32, 36, 331, DateTimeKind.Local).AddTicks(5186),
                            DefaultDays = 15,
                            Name = "Remote Work",
                            RequiresHRApproval = true,
                            Uid = new Guid("31095778-f45a-4505-ae6e-5516ee2f32aa")
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 11, 26, 0, 32, 36, 331, DateTimeKind.Local).AddTicks(5188),
                            DefaultDays = 365,
                            Name = "Sick Leave",
                            RequiresHRApproval = false,
                            Uid = new Guid("e4c95136-ec9c-4892-99d2-eff806f61bb3")
                        });
                });

            modelBuilder.Entity("Core.Domain.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LeadUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 26, 0, 32, 36, 331, DateTimeKind.Local).AddTicks(6752),
                            LeadUid = new Guid("306627f3-c902-4d48-a6f3-d83db48df2c6"),
                            Name = "GBI",
                            Uid = new Guid("9fe876b5-0429-42e0-a205-1f6d9c2a7cb5")
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 26, 0, 32, 36, 331, DateTimeKind.Local).AddTicks(6772),
                            LeadUid = new Guid("985fe5c1-deb8-4082-863a-840037477bc5"),
                            Name = "GOAT",
                            Uid = new Guid("bd7746a3-1385-4d0e-8fb7-3e19a0f360c1")
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 26, 0, 32, 36, 331, DateTimeKind.Local).AddTicks(6778),
                            LeadUid = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Support",
                            Uid = new Guid("67f55a17-fc74-4c83-ad93-e52937c2499c")
                        });
                });

            modelBuilder.Entity("Core.Domain.TeamUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TeamUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserUid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TeamsUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 11, 25, 23, 32, 36, 331, DateTimeKind.Utc).AddTicks(7821),
                            TeamUid = new Guid("9fe876b5-0429-42e0-a205-1f6d9c2a7cb5"),
                            Uid = new Guid("cd96d88b-9a54-4a70-b8bc-9b49c56b3ba8"),
                            UserUid = new Guid("2499bc5a-0f33-4f67-b521-5829679ee7ff")
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 11, 25, 23, 32, 36, 331, DateTimeKind.Utc).AddTicks(7834),
                            TeamUid = new Guid("9fe876b5-0429-42e0-a205-1f6d9c2a7cb5"),
                            Uid = new Guid("6046269d-7248-42c0-9799-d793987b8c5d"),
                            UserUid = new Guid("e19c3b4a-b3ec-49a8-9790-5d15d9b8de96")
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 11, 25, 23, 32, 36, 331, DateTimeKind.Utc).AddTicks(7837),
                            TeamUid = new Guid("67f55a17-fc74-4c83-ad93-e52937c2499c"),
                            Uid = new Guid("3a47687c-1119-46be-b2df-78185fd2f13d"),
                            UserUid = new Guid("306627f3-c902-4d48-a6f3-d83db48df2c6")
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 11, 25, 23, 32, 36, 331, DateTimeKind.Utc).AddTicks(7838),
                            TeamUid = new Guid("bd7746a3-1385-4d0e-8fb7-3e19a0f360c1"),
                            Uid = new Guid("0e2fb292-3f7b-44e9-8e74-a3e1466ecb79"),
                            UserUid = new Guid("985fe5c1-deb8-4082-863a-840037477bc5")
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 11, 25, 23, 32, 36, 331, DateTimeKind.Utc).AddTicks(7840),
                            TeamUid = new Guid("bd7746a3-1385-4d0e-8fb7-3e19a0f360c1"),
                            Uid = new Guid("67cb7503-7296-481e-a48a-e44049d26feb"),
                            UserUid = new Guid("88ea1648-4810-4e04-81f9-cfdff02bbd22")
                        });
                });

            modelBuilder.Entity("Core.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateOfEmployment")
                        .HasColumnType("date");

                    b.Property<Guid?>("DedicatedHR")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsTeamLead")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("ReligiousHolidayDay")
                        .HasColumnType("date");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TeamLeadUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyEmail = "admin@localhost.com",
                            CreatedDate = new DateTime(2024, 11, 25, 23, 32, 36, 331, DateTimeKind.Utc).AddTicks(8683),
                            DateOfBirth = new DateOnly(1, 1, 1),
                            DateOfEmployment = new DateOnly(1, 1, 1),
                            FirstName = "System",
                            IsTeamLead = false,
                            LastName = "Admin",
                            Seniority = "Unknown",
                            StackPosition = "Unknown",
                            Uid = new Guid("42df1250-85ef-4683-9046-6f2e5405ee3a")
                        },
                        new
                        {
                            Id = 2,
                            CompanyEmail = "naissuscompanyadmin@localhost.com",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 25, 23, 32, 36, 331, DateTimeKind.Utc).AddTicks(8691),
                            DateOfBirth = new DateOnly(1, 1, 1),
                            DateOfEmployment = new DateOnly(1, 1, 1),
                            FirstName = "Company",
                            IsTeamLead = false,
                            LastName = "Admin",
                            Seniority = "Unknown",
                            StackPosition = "Unknown",
                            Uid = new Guid("48a3b0de-d24d-4879-a528-ddaf38580270")
                        },
                        new
                        {
                            Id = 3,
                            CompanyEmail = "filip.dimitrijevic@localhost.com",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 25, 23, 32, 36, 331, DateTimeKind.Utc).AddTicks(8694),
                            DateOfBirth = new DateOnly(1995, 1, 14),
                            DateOfEmployment = new DateOnly(2021, 1, 10),
                            DedicatedHR = new Guid("306627f3-c902-4d48-a6f3-d83db48df2c6"),
                            FirstName = "Filip",
                            IsTeamLead = false,
                            LastName = "Dimitrijevic",
                            ReligiousHolidayDay = new DateOnly(1900, 1, 12),
                            Seniority = "Mid",
                            StackPosition = "Backend",
                            TeamLeadUid = new Guid("e19c3b4a-b3ec-49a8-9790-5d15d9b8de96"),
                            Uid = new Guid("2499bc5a-0f33-4f67-b521-5829679ee7ff")
                        },
                        new
                        {
                            Id = 4,
                            CompanyEmail = "hr@localhost.com",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 25, 23, 32, 36, 331, DateTimeKind.Utc).AddTicks(8701),
                            DateOfBirth = new DateOnly(1990, 1, 1),
                            DateOfEmployment = new DateOnly(2022, 1, 1),
                            FirstName = "Bojana",
                            IsTeamLead = false,
                            LastName = "Stoiljkovic",
                            Seniority = "Mid",
                            StackPosition = "HR",
                            Uid = new Guid("306627f3-c902-4d48-a6f3-d83db48df2c6")
                        },
                        new
                        {
                            Id = 5,
                            CompanyEmail = "marko.stoiljkovic@localhost.com",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 25, 23, 32, 36, 331, DateTimeKind.Utc).AddTicks(8703),
                            DateOfBirth = new DateOnly(1989, 1, 1),
                            DateOfEmployment = new DateOnly(2015, 1, 1),
                            DedicatedHR = new Guid("306627f3-c902-4d48-a6f3-d83db48df2c6"),
                            FirstName = "Marko",
                            IsTeamLead = true,
                            LastName = "Stoiljkovic",
                            ReligiousHolidayDay = new DateOnly(1900, 1, 12),
                            Seniority = "Lead",
                            StackPosition = "ProjectManager",
                            Uid = new Guid("e19c3b4a-b3ec-49a8-9790-5d15d9b8de96")
                        },
                        new
                        {
                            Id = 6,
                            CompanyEmail = "sara.dimitrijevic@localhost.com",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 25, 23, 32, 36, 331, DateTimeKind.Utc).AddTicks(8705),
                            DateOfBirth = new DateOnly(1999, 2, 12),
                            DateOfEmployment = new DateOnly(2020, 1, 1),
                            DedicatedHR = new Guid("306627f3-c902-4d48-a6f3-d83db48df2c6"),
                            FirstName = "Sara",
                            IsTeamLead = true,
                            LastName = "Dimitrijevic",
                            ReligiousHolidayDay = new DateOnly(1900, 1, 12),
                            Seniority = "Mid",
                            StackPosition = "ProjectManager",
                            Uid = new Guid("985fe5c1-deb8-4082-863a-840037477bc5")
                        },
                        new
                        {
                            Id = 7,
                            CompanyEmail = "petar.markovic@localhost.com",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 11, 25, 23, 32, 36, 331, DateTimeKind.Utc).AddTicks(8708),
                            DateOfBirth = new DateOnly(1998, 12, 5),
                            DateOfEmployment = new DateOnly(2021, 1, 1),
                            DedicatedHR = new Guid("306627f3-c902-4d48-a6f3-d83db48df2c6"),
                            FirstName = "Petar",
                            IsTeamLead = false,
                            LastName = "Markovic",
                            ReligiousHolidayDay = new DateOnly(1900, 1, 12),
                            Seniority = "Senior",
                            StackPosition = "Backend",
                            TeamLeadUid = new Guid("985fe5c1-deb8-4082-863a-840037477bc5"),
                            Uid = new Guid("88ea1648-4810-4e04-81f9-cfdff02bbd22")
                        });
                });

            modelBuilder.Entity("Core.Domain.Candidate", b =>
                {
                    b.HasOne("Core.Domain.Company", "Company")
                        .WithMany("Candidates")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Core.Domain.LeaveDistribution", b =>
                {
                    b.HasOne("Core.Domain.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("Core.Domain.LeaveRequest", b =>
                {
                    b.HasOne("Core.Domain.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Core.Domain.Common.DateRange", "Duration", b1 =>
                        {
                            b1.Property<int>("LeaveRequestId")
                                .HasColumnType("int");

                            b1.Property<DateOnly>("End")
                                .HasColumnType("date");

                            b1.Property<int>("LengthInDays")
                                .HasColumnType("int");

                            b1.Property<DateOnly>("Start")
                                .HasColumnType("date");

                            b1.HasKey("LeaveRequestId");

                            b1.ToTable("LeaveRequests");

                            b1.WithOwner()
                                .HasForeignKey("LeaveRequestId");
                        });

                    b.Navigation("Duration")
                        .IsRequired();

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("Core.Domain.Team", b =>
                {
                    b.HasOne("Core.Domain.Company", "Company")
                        .WithMany("Teams")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Core.Domain.User", b =>
                {
                    b.HasOne("Core.Domain.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Core.Domain.Company", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("Teams");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
