// <auto-generated />
using System;
using Core.Infrastructure.Persistence.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Infrastructure.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20241204142256_RenameDedicatedToAssignedHR")]
    partial class RenameDedicatedToAssignedHR
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CVPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CVPath = "/uploads/john_doe_cv.pdf",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 12, 4, 14, 22, 55, 700, DateTimeKind.Utc).AddTicks(1617),
                            DateOfBirth = new DateOnly(1990, 5, 15),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Note = "Candidate shows strong skills in backend development.",
                            Rating = 4,
                            Seniority = "Senior",
                            StackPosition = "Backend",
                            Uid = new Guid("94e5b089-3ac2-4e7c-bb5a-11c0ea67570a")
                        },
                        new
                        {
                            Id = 2,
                            CVPath = "/uploads/alice_smith_cv.pdf",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 12, 4, 14, 22, 55, 700, DateTimeKind.Utc).AddTicks(1657),
                            DateOfBirth = new DateOnly(1985, 12, 30),
                            Email = "alice.smith@example.com",
                            FirstName = "Alice",
                            LastName = "Smith",
                            Note = "Experienced project manager with a strong background in Agile methodologies.",
                            Rating = 5,
                            Seniority = "Senior",
                            StackPosition = "Fullstack",
                            Uid = new Guid("d3e83815-0605-49d9-b6e7-65486db5add5")
                        },
                        new
                        {
                            Id = 3,
                            CVPath = "/uploads/michael_johnson_cv.pdf",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 12, 4, 14, 22, 55, 700, DateTimeKind.Utc).AddTicks(1660),
                            DateOfBirth = new DateOnly(1992, 4, 10),
                            Email = "michael.johnson@example.com",
                            FirstName = "Michael",
                            LastName = "Johnson",
                            Note = "Front-end developer with expertise in React and Vue.js.",
                            Rating = 3,
                            Seniority = "Junior",
                            StackPosition = "Unknown",
                            Uid = new Guid("c3e21813-4e8e-4aeb-8987-62ad85aff1ac")
                        },
                        new
                        {
                            Id = 4,
                            CVPath = "/uploads/emma_williams_cv.pdf",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 12, 4, 14, 22, 55, 700, DateTimeKind.Utc).AddTicks(1662),
                            DateOfBirth = new DateOnly(1988, 8, 25),
                            Email = "emma.williams@example.com",
                            FirstName = "Emma",
                            LastName = "Williams",
                            Note = "Full-stack developer with strong skills in Node.js and .NET Core.",
                            Rating = 4,
                            Seniority = "Junior",
                            StackPosition = "Fullstack",
                            Uid = new Guid("047e274b-8644-478a-b398-1fb65fa09fa5")
                        },
                        new
                        {
                            Id = 5,
                            CVPath = "/uploads/david_brown_cv.pdf",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 12, 4, 14, 22, 55, 700, DateTimeKind.Utc).AddTicks(1664),
                            DateOfBirth = new DateOnly(1995, 11, 15),
                            Email = "david.brown@example.com",
                            FirstName = "David",
                            LastName = "Brown",
                            Note = "DevOps engineer with experience in CI/CD pipelines and containerization.",
                            Rating = 5,
                            Seniority = "Mid",
                            StackPosition = "DevOps",
                            Uid = new Guid("52bb1802-696c-4a97-ba6d-2320d58e4cfd")
                        });
                });

            modelBuilder.Entity("Core.Domain.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 12, 4, 15, 22, 55, 700, DateTimeKind.Local).AddTicks(2493),
                            Name = "Naissus Tech",
                            Uid = new Guid("da4fdc93-facb-45e2-9170-cb94d01c42fb")
                        });
                });

            modelBuilder.Entity("Core.Domain.LeaveDistribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeUid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<int>("RemainingDays")
                        .HasColumnType("int");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveDistributions");
                });

            modelBuilder.Entity("Core.Domain.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRequested")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<string>("RequestComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestingEmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReserveOnly")
                        .HasColumnType("bit");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("Core.Domain.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DefaultDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("RequiresHRApproval")
                        .HasColumnType("bit");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LeaveTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 12, 4, 15, 22, 55, 700, DateTimeKind.Local).AddTicks(3922),
                            DefaultDays = 21,
                            Name = "Vacation",
                            RequiresHRApproval = true,
                            Uid = new Guid("24c4f37a-ac86-4839-b40c-41f04deaa835")
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 12, 4, 15, 22, 55, 700, DateTimeKind.Local).AddTicks(3938),
                            DefaultDays = 15,
                            Name = "Old Vacation",
                            RequiresHRApproval = true,
                            Uid = new Guid("968ab0e1-b469-460e-9ce3-8141e2c52adc")
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 12, 4, 15, 22, 55, 700, DateTimeKind.Local).AddTicks(3940),
                            DefaultDays = 15,
                            Name = "Remote Work",
                            RequiresHRApproval = true,
                            Uid = new Guid("caac097b-7568-41a7-9031-0a0a75f9e01c")
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 12, 4, 15, 22, 55, 700, DateTimeKind.Local).AddTicks(3946),
                            DefaultDays = 365,
                            Name = "Sick Leave",
                            RequiresHRApproval = false,
                            Uid = new Guid("60169956-bf2d-4f74-8844-01c8ddead5ab")
                        });
                });

            modelBuilder.Entity("Core.Domain.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LeadUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 12, 4, 15, 22, 55, 700, DateTimeKind.Local).AddTicks(5421),
                            LeadUid = new Guid("306627f3-c902-4d48-a6f3-d83db48df2c6"),
                            Name = "GBI",
                            Uid = new Guid("9fe876b5-0429-42e0-a205-1f6d9c2a7cb5")
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 12, 4, 15, 22, 55, 700, DateTimeKind.Local).AddTicks(5443),
                            LeadUid = new Guid("985fe5c1-deb8-4082-863a-840037477bc5"),
                            Name = "GOAT",
                            Uid = new Guid("bd7746a3-1385-4d0e-8fb7-3e19a0f360c1")
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 12, 4, 15, 22, 55, 700, DateTimeKind.Local).AddTicks(5448),
                            LeadUid = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Support",
                            Uid = new Guid("67f55a17-fc74-4c83-ad93-e52937c2499c")
                        });
                });

            modelBuilder.Entity("Core.Domain.TeamUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TeamUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserUid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TeamsUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 12, 4, 14, 22, 55, 700, DateTimeKind.Utc).AddTicks(6412),
                            TeamUid = new Guid("9fe876b5-0429-42e0-a205-1f6d9c2a7cb5"),
                            Uid = new Guid("d30e9f77-dab0-401d-9081-14abe683b50e"),
                            UserUid = new Guid("2499bc5a-0f33-4f67-b521-5829679ee7ff")
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 12, 4, 14, 22, 55, 700, DateTimeKind.Utc).AddTicks(6423),
                            TeamUid = new Guid("9fe876b5-0429-42e0-a205-1f6d9c2a7cb5"),
                            Uid = new Guid("664eacfc-cdd3-472c-93cf-6b506f76f93d"),
                            UserUid = new Guid("e19c3b4a-b3ec-49a8-9790-5d15d9b8de96")
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 12, 4, 14, 22, 55, 700, DateTimeKind.Utc).AddTicks(6426),
                            TeamUid = new Guid("67f55a17-fc74-4c83-ad93-e52937c2499c"),
                            Uid = new Guid("bec72a20-5642-4835-92f4-7e7a49229aec"),
                            UserUid = new Guid("306627f3-c902-4d48-a6f3-d83db48df2c6")
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 12, 4, 14, 22, 55, 700, DateTimeKind.Utc).AddTicks(6428),
                            TeamUid = new Guid("bd7746a3-1385-4d0e-8fb7-3e19a0f360c1"),
                            Uid = new Guid("91624d6e-f33c-431f-b510-38df55110c2a"),
                            UserUid = new Guid("985fe5c1-deb8-4082-863a-840037477bc5")
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 12, 4, 14, 22, 55, 700, DateTimeKind.Utc).AddTicks(6430),
                            TeamUid = new Guid("bd7746a3-1385-4d0e-8fb7-3e19a0f360c1"),
                            Uid = new Guid("d279f990-ba4a-4313-b2ea-23fe246bdac9"),
                            UserUid = new Guid("88ea1648-4810-4e04-81f9-cfdff02bbd22")
                        });
                });

            modelBuilder.Entity("Core.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AssignedHR")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateOfEmployment")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsTeamLead")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ReligiousHolidayDay")
                        .HasColumnType("date");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TeamLeadUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyEmail = "admin@localhost.com",
                            CreatedDate = new DateTime(2024, 12, 4, 14, 22, 55, 700, DateTimeKind.Utc).AddTicks(7298),
                            DateOfBirth = new DateOnly(1, 1, 1),
                            DateOfEmployment = new DateOnly(1, 1, 1),
                            FirstName = "System",
                            IsTeamLead = false,
                            LastName = "Admin",
                            Seniority = "Unknown",
                            StackPosition = "Unknown",
                            Uid = new Guid("42df1250-85ef-4683-9046-6f2e5405ee3a")
                        },
                        new
                        {
                            Id = 2,
                            CompanyEmail = "naissuscompanyadmin@localhost.com",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 12, 4, 14, 22, 55, 700, DateTimeKind.Utc).AddTicks(7305),
                            DateOfBirth = new DateOnly(1, 1, 1),
                            DateOfEmployment = new DateOnly(1, 1, 1),
                            FirstName = "Company",
                            IsTeamLead = false,
                            LastName = "Admin",
                            Seniority = "Unknown",
                            StackPosition = "Unknown",
                            Uid = new Guid("48a3b0de-d24d-4879-a528-ddaf38580270")
                        },
                        new
                        {
                            Id = 3,
                            AssignedHR = new Guid("306627f3-c902-4d48-a6f3-d83db48df2c6"),
                            CompanyEmail = "filip.dimitrijevic@localhost.com",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 12, 4, 14, 22, 55, 700, DateTimeKind.Utc).AddTicks(7308),
                            DateOfBirth = new DateOnly(1995, 1, 14),
                            DateOfEmployment = new DateOnly(2021, 1, 10),
                            FirstName = "Filip",
                            IsTeamLead = false,
                            LastName = "Dimitrijevic",
                            PhoneNumber = "0692509999",
                            ReligiousHolidayDay = new DateOnly(1900, 1, 12),
                            Seniority = "Mid",
                            StackPosition = "Backend",
                            TeamLeadUid = new Guid("e19c3b4a-b3ec-49a8-9790-5d15d9b8de96"),
                            Uid = new Guid("2499bc5a-0f33-4f67-b521-5829679ee7ff")
                        },
                        new
                        {
                            Id = 4,
                            CompanyEmail = "hr@localhost.com",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 12, 4, 14, 22, 55, 700, DateTimeKind.Utc).AddTicks(7316),
                            DateOfBirth = new DateOnly(1990, 1, 1),
                            DateOfEmployment = new DateOnly(2022, 1, 1),
                            FirstName = "Bojana",
                            IsTeamLead = false,
                            LastName = "Stoiljkovic",
                            Seniority = "Mid",
                            StackPosition = "HR",
                            Uid = new Guid("306627f3-c902-4d48-a6f3-d83db48df2c6")
                        },
                        new
                        {
                            Id = 5,
                            AssignedHR = new Guid("306627f3-c902-4d48-a6f3-d83db48df2c6"),
                            CompanyEmail = "marko.stoiljkovic@localhost.com",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 12, 4, 14, 22, 55, 700, DateTimeKind.Utc).AddTicks(7318),
                            DateOfBirth = new DateOnly(1989, 1, 1),
                            DateOfEmployment = new DateOnly(2015, 1, 1),
                            FirstName = "Marko",
                            IsTeamLead = true,
                            LastName = "Stoiljkovic",
                            PhoneNumber = "0638888888",
                            ReligiousHolidayDay = new DateOnly(1900, 1, 12),
                            Seniority = "Lead",
                            StackPosition = "ProjectManager",
                            Uid = new Guid("e19c3b4a-b3ec-49a8-9790-5d15d9b8de96")
                        },
                        new
                        {
                            Id = 6,
                            AssignedHR = new Guid("306627f3-c902-4d48-a6f3-d83db48df2c6"),
                            CompanyEmail = "sara.dimitrijevic@localhost.com",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 12, 4, 14, 22, 55, 700, DateTimeKind.Utc).AddTicks(7321),
                            DateOfBirth = new DateOnly(1999, 2, 12),
                            DateOfEmployment = new DateOnly(2020, 1, 1),
                            FirstName = "Sara",
                            IsTeamLead = true,
                            LastName = "Dimitrijevic",
                            PhoneNumber = "0623333344",
                            ReligiousHolidayDay = new DateOnly(1900, 1, 12),
                            Seniority = "Mid",
                            StackPosition = "ProjectManager",
                            Uid = new Guid("985fe5c1-deb8-4082-863a-840037477bc5")
                        },
                        new
                        {
                            Id = 7,
                            AssignedHR = new Guid("306627f3-c902-4d48-a6f3-d83db48df2c6"),
                            CompanyEmail = "petar.markovic@localhost.com",
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 12, 4, 14, 22, 55, 700, DateTimeKind.Utc).AddTicks(7324),
                            DateOfBirth = new DateOnly(1998, 12, 5),
                            DateOfEmployment = new DateOnly(2021, 1, 1),
                            FirstName = "Petar",
                            IsTeamLead = false,
                            LastName = "Markovic",
                            ReligiousHolidayDay = new DateOnly(1900, 1, 12),
                            Seniority = "Senior",
                            StackPosition = "Backend",
                            TeamLeadUid = new Guid("985fe5c1-deb8-4082-863a-840037477bc5"),
                            Uid = new Guid("88ea1648-4810-4e04-81f9-cfdff02bbd22")
                        });
                });

            modelBuilder.Entity("Core.Domain.Candidate", b =>
                {
                    b.HasOne("Core.Domain.Company", "Company")
                        .WithMany("Candidates")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Core.Domain.LeaveDistribution", b =>
                {
                    b.HasOne("Core.Domain.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("Core.Domain.LeaveRequest", b =>
                {
                    b.HasOne("Core.Domain.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Core.Domain.Common.DateRange", "Duration", b1 =>
                        {
                            b1.Property<int>("LeaveRequestId")
                                .HasColumnType("int");

                            b1.Property<DateOnly>("End")
                                .HasColumnType("date");

                            b1.Property<int>("LengthInDays")
                                .HasColumnType("int");

                            b1.Property<DateOnly>("Start")
                                .HasColumnType("date");

                            b1.HasKey("LeaveRequestId");

                            b1.ToTable("LeaveRequests");

                            b1.WithOwner()
                                .HasForeignKey("LeaveRequestId");
                        });

                    b.Navigation("Duration")
                        .IsRequired();

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("Core.Domain.Team", b =>
                {
                    b.HasOne("Core.Domain.Company", "Company")
                        .WithMany("Teams")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Core.Domain.User", b =>
                {
                    b.HasOne("Core.Domain.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Core.Domain.Company", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("Teams");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
